### ISSUE TITLE
Authentication failing 

### ISSUE THREAD

**Issue by rathnaum** [evernote/evernote-cloud-sdk-windows#1]
The below code to authenticate to EN with OAuth is throwing exception.

ENSession.SetSharedSessionConsumerKey(EVERNOTE_CONSUMER_KEY, EVERNOTE_CONSUMER_SECRET, EVERNOTE_SANDBOX_URL);

```
        if (ENSession.SharedSession.IsAuthenticated == false)
        {
            // Evernote API is throwing NullReference exception
            ENSession.SharedSession.AuthenticateToEvernote();
        }
```

**Comment by mpnow** [comment]
Fixed this - added check to make sure NotebooksCache is not null before clearing it.
