### ISSUE TITLE
Generating oAuth token

### ISSUE THREAD

**Issue by adrianhalid** [evernote/evernote-cloud-sdk-windows#14]
Is there a way to generate the oAuth token using the Evernote windows SDK?

If I am building a C# MVC web application how do I create the temporary token and process the access token. https://dev.evernote.com/doc/articles/authentication.php

I can't use the ENSession.SharedSession.AuthenticateToEvernote(); as it is not a desktop application.

Isn't there some methods like in the PHP version of the library to create and process the tokens.

Create Token
$oauth_data  = $oauth_handler->authorize($key, $secret, $callback);

Process Token
$client = new \Evernote\Client($token, $sandbox);

I did find https://github.com/shaunmccarthy/AsyncOAuth.Evernote.Simple which uses the asyncOAuth library and calls Evernote cloud API directly.

But I would have thought that this Evernote cloud SDK would have these features already.

**Comment by mpnow** [comment]
There isn't currently a web-friendly OAuth function in the Windows API.  Your best bet is probably to use Shaun McCarthy's OAuth which you've already found.
