### ISSUE TITLE
Unable to perform a search on all Notes.

### ISSUE THREAD

**Issue by jaycdave88** [evernote/evernote-cloud-sdk-windows#18]
I currently have am performing a search where I return all the notes that are associated to a my sandbox.evernote.com account. Currently I my AuthToken and NotebookURL hard coded, which is working perfect. 

However I am using AsyncOAuth.Evernote.Simple lib to perform an OAuth before hitting the search function. I am getting a strange behavior, while my AuthToken and NotebookURL are hardcoded in - everything works. When I use the OAuth - it breaks, have compared both the AuthTokens and they are different.

Does the search not work with a OAuth token that are not your Dev Token? 

`List<ENSessionFindNotesResult> myResultsList = ENSession.SharedSession.FindNotes(ENNoteSearch.NoteSearch(textToFindPattern), null, ENSession.SearchScope.All, ENSession.SortOrder.RecentlyUpdated, 500);` is what I am calling to create the list of notes, but I run into this error - `Exception of type 'Evernote.EDAM.Error.EDAMUserException' was thrown.`

**Comment by mpnow** [comment]
Yeah, a Developer token and an OAuth token are not interchangeable.  I gather what you're trying is to call SetSharedSessionDeveloperToken passing in the OAuth token you got from AsyncOAuth.Evernote.Simple.  Don't think that's going to work.

At the moment, the Windows SDK expects that you'll be authenticating using the AuthenticateToEvernote method, which uses its own EvernoteOAuth library internally.  What would probably be needed is to extend the library by supporting the option to pass authentication info into the AuthenticateToEvernote method, which internally would then say "oh cool, I received authentication info, I can bypass doing the authentication myself".  Not sure if that's something you want to tackle adding to the SDK...

**Comment by jaycdave88** [comment]
Thank you for your quick response. I understand now why I was getting the Evernote.EDAM.EDAMUserException error. 

I have taken your suggestion and am trying to add to the lib - however I am unable to build my code to test if it works I keep getting this error "Severity Code Description Project File Line Suppression State Error Cannot register assembly"

Is this something that you have seen before? 

***Never mind - had to do with my assemblies being within the code and not outside

**Comment by bpacy27** [comment]
I'm working with @jaycdave88 on this and spent a little more time digging into the issue.
What's odd is that even if we are using the OAuth token, we can still pull back notebook names when it gets the list of notebooks.  So it looks like we're authenticating properly?  We fail somewhere in the ENNoteStoreClient.FindNotesMetaData() method and the error code we are getting is Evernote.EDAM.Error.EDAMErrorCode.PERMISSION_DENIED.

Does this mean anything different or do you think we still need to edit the AuthenticateToEvernote() method?

**Comment by mpnow** [comment]
Can you post the complete code you guys are using?  It's difficult know exactly what you're trying just from the descriptions and code snippet.

**Comment by jaycdave88** [comment]
Thank you @mpnow, however we have it working. You can in fact use an OAuth token in place of a Developer token. The issue we were having was an Evernote access issue.
