### ISSUE TITLE
I'm getting the "Compile Error: User-Defined Error Type not Defined" in the below code, i don't understand the problem

### ISSUE THREAD

**Issue by FRZ0** [evernote/evernote-cloud-sdk-windows#39]
Sub GetFromOutlook ()

Dim OutlookApp As Outlook.Application
Dim OutlookNamespace As Namespace
Dim Folder As MAPIFolder
Dim OutlookMail As Variant
Dim i As Integer

Set OutlookApp = New Outlook.Application
Set OutlookNamespace = OutlookApp.GetNamespace("MAPI")
Set Folder = OutlookNamespace.GetDefaultFolder(olFolderInbox).Folders("Net Sales Report").Folders("Sales")

i = 1

For Each OutlookMail In Folder.Items
    If OutlookMail.ReceivedTime >= Range("From_date").Value Then
        Range("eMail_subject").Offset(i, 0).Value = OutlookMail.Subject
        Range("eMail_date").Offset(i, 0).Value = OutlookMail.ReceivedTime
        Range("eMail_sender").Offset(i, 0).Value = OutlookMail.SenderName
        Range("eMail_text").Offset(i, 0).Value = OutlookMail.Body
        
        i = i + 1
    End If
Next OutlookMail

Set Folder = Nothing
Set OutlookNamespace = Nothing
Set OutlookApp = Nothing

End Sub

**Comment by FRZ0** [comment]
I can't seem to understand the issue

**Comment by FRZ0** [comment]
I have made sure  that the latest Microsft active X Data object library is ticked and still won't work

**Comment by mpnow** [comment]
You'll also need to check off the reference to the Microsoft Outlook xx.0 Object Library.

But note that this issue isn't related to Evernote or its SDK; if you need further assistance on this issue, it's best to post it on a Microsoft support forum.
